name: pyproject
description: 0compute Python shared

inputs:
  cachix-authToken:
    description: Cachix auth token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: ${{ github.event.repository.name }}
        authToken: ${{ inputs.cachix-authToken }}
    - uses: JRMurr/direnv-nix-action@v4.1.0
      with:
        install-nix: false
        cache-store: false
