name: pyproject
description: 0compute Python shared

inputs:
  cachix-authToken:
    description: Cachix auth token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: DeterminateSystems/nix-installer-action@v6
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: cachix/cachix-action@v12
      with:
        name: ${{ github.event.repository.name }}
        authToken: ${{ inputs.cachix-authToken }}
    - uses: JRMurr/direnv-nix-action@v4.1.0
      with:
        install-nix: false
        cache-store: false
