name: pyproject
description: 0compute Python shared

inputs:
  cachix-authToken:
    description: Cachix auth token
    required: true

runs:
  using: composite
  steps:
    - uses: nixbuild/nix-quick-install-action@v29
    - uses: nix-community/cache-nix-action@v5
      with:
        primary-key: nix-${{ runner.os }}
    - uses: cachix/cachix-action@v15
      with:
        name: ${{ github.event.repository.name }}
        authToken: ${{ inputs.cachix-authToken }}
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: nix build ".#devShells.$(nix eval --impure --raw --expr builtins.currentSystem).default"
      shell: bash
